# Site settings
title: template0
subtitle: table yangming;
email: sdwhlym@126.com
description: "open up the wasteland of brain"
logo_location: "/image/sar.png"

#baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
permalink:        /:month-:year/:title:output_ext

# Build settings
markdown: kramdown
kramdown:
  input: GFM

highlighter: rouge

#Other Global Configuration
exclude: ['README.md']

excerpt_separator: <!--more-->

#show the jumbotron header on index page
show_blog_header: false

# Disqus settings
#disqus_username: yummyliu
disqus: yes
disqus_id: yummyliu-github-io-1
org_site: liuyangming.tech
# Analytics settings
# Baidu Analytics
ba_track_id: 59b5c72c98ed6bb90d190b2bf7cd2cbb

ga_track_id: 'UA-80816254-1'            # Format: UA-xxxxxx-xx-80816254-1
#ga_track_id: 'UA-122987085-1'            # Format: UA-xxxxxx-xx-80816254-1
ga_domain: liuyangming.tech


